branches:
 only:
  - master

matrix:
  include:
   - os: linux
     dist: precise
     language: generic
     env: TRAVIS_PYTHON_VERSION=3.4  CC=gcc-4.4 FC=gfortran-4.4  CXX=g++-4.4
     addons:
      apt:
       packages:
       - gfortran-4.4
       - gcc-4.4
       - g++-4.4
       - tcl-dev
       - libatlas-dev
       - libblas-dev
       - liblapack-dev
       - libatlas-base-dev

install:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
 - if [ "$TRAVIS_OS_NAME" == "windows" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.sh -O miniconda.sh; fi

 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes 
 - conda install anaconda conda-build -y

 - conda create -q -n travis-env python=$TRAVIS_PYTHON_VERSION 
 - source activate travis-env

 - git describe --tags
 - export BUILD_VERSION=$(git describe --tags | sed 's/-/ /g' | awk '{print $1}')
 - export BUILD_NUMBER=$(git describe --tags | sed 's/-/ /g' | awk '{print $2}')
 # Always set it to 0 so we don't get a new release at every successful commit
 - export BUILD_NUMBER=0

 - DD="$PWD"
 - cd "$HOME"
 - wget http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/cuda_7.5.18_linux.run
 - chmod +x cuda_7.5.18_linux.run
 - ./cuda_7.5.18_linux.run --silent --toolkit --toolkitpath=$PWD
 - wget --no-check-certificate http://cmake.org/files/v3.5/cmake-3.5.0-Linux-x86_64.tar.gz
 - tar -zxvf cmake-3.5.0-Linux-x86_64.tar.gz
 - ln -s cmake-3.5.0-Linux-x86_64 cmake
 - cd "$DD"

 - conda build --python $TRAVIS_PYTHON_VERSION package/
 - conda install gromacs --use-local

script:

after_success:
 - export PATH="$HOME/miniconda/bin:$PATH"
 - echo $PATH
 - anaconda -t $ANACONDA_TOKEN upload  $HOME/miniconda/conda-bld/*-64/gromacs-[0-9]*.tar.bz2 -u acellera  --force || /usr/bin/true 


