package:
 name: gromacs
 version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }}

build:
 number: {{ environ.get('BUILD_NUMBER', 0 ) }}

requirements:
 build:

 run:
  - python >=2.7

about:
 license: "LGPL"

